### ISSUE TITLE
Bug: ubuntu 18.04 amber intstallation

### ISSUE THREAD

**Issue by zenny** [amberframework/amber#809]
HI,

In ubuntu 18.04, amberframework fails to build with the openssl issue:

```
~/amber-stable# make install
Building amber in /root/amber-stable/bin/amber
_main.o: In function `__crystal_main':                
main_module:(.text+0xeb8): undefined reference to `SSL_library_init'
main_module:(.text+0xebd): undefined reference to `SSL_load_error_strings'
main_module:(.text+0xec2): undefined reference to `OPENSSL_add_all_algorithms_noconf'
main_module:(.text+0xec7): undefined reference to `ERR_load_crypto_strings'
O-penS-S-L-5858S-S-L-5858C-ontext.o: In function `*OpenSSL::SSL::Context::default_method:Pointer(Void)':
OpenSSL::SSL::Context:(.text+0x2): undefined reference to `SSLv23_method'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/root/amber-stable/bin/amber'  -rdynamic  -lsqlite3 `command -v pkg-config > /dev/null && pkg-config --libs libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs libcrypto || printf %s '-lcrypto'` -lyaml -lpcre -lm -lgc -lpthread /usr/share/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
Makefile:17: recipe for target '/root/amber-stable/bin/amber' failed
make: *** [/root/amber-stable/bin/amber] Error 1
```

But builds fine in ubuntu 16.04.

**Comment by faustinoaq** [comment]
@docelic Are you using ubuntu 18.04, Did you have a similar issue?

@zenny I think amber guides are a bit outdated, so the dependencies may be changed, if you found a fix for this, please feel free to contribute with [Guides/Installation](https://amberframework.gitbook.io/amber/guides/installation)

![screenshot_20180521_073354](https://user-images.githubusercontent.com/3067335/40307729-52da00ae-5cc9-11e8-9797-2e3456526a92.png)

We have a nice **Edit on Github** button now :wink:

**Comment by docelic** [comment]
@faustinoaq never seen that issue myself.

**Comment by faustinoaq** [comment]
@docelic Maybe we should update dependencies in amber guide, see: [Installation for Debian & Ubuntu](https://amberframework.gitbook.io/amber/guides/installation#for-debian-and-ubuntu)

**Comment by Rojo** [comment]
@zenny @faustinoaq I had this same issue.

It was resolved following the advice of installing dependencies with [`apt buildep nginx`](https://github.com/amberframework/amber/issues/487#issuecomment-356044099) . Some of these have the missing files required for compiling.

**Comment by faustinoaq** [comment]
@Rojo Oh, nice :+1: , maybe we should update [Installation guide](https://amberframework.gitbook.io/amber/guides/installation) or add a new section on [Amber troubleshooting](https://amberframework.gitbook.io/amber/troubleshooting), WDYT?

**Comment by Rojo** [comment]
@faustinoaq It would be nice to identify which of those packages are the required ones and add them to the guide, 'cause the build dependencies for nginx are a lot. But, since it is a workaround, I think a troubleshooting note at the installation instructions, that points to this particular error, would do.

**Comment by faustinoaq** [comment]
@lcdss Yeah, see #826

**Comment by drujensen** [comment]
I believe this has been addressed.  If not, please re-open.
